AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  BucketName:
    Type: String
    Default: dakobed-lach-orders
Resources:
  ProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://dakobed-serverless-apis/8651a4b653357f96f1603bd5182d8a83
      Handler: app.lambda_handler
      Runtime: python3.7
      Tracing: Active
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream:
              Fn::GetAtt:
              - OrdersStream
              - Arn
            BatchSize: 100
            StartingPosition: LATEST
