AWSTemplateFormatVersion: 2010-09-09
Description: Stack for Firehose DeliveryStream S3 Destination.

Parameters:
  BucketName:
    Type: String
    Default: dakobed-lach-orders


Resources:
  s3bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Suspended
      AccessControl: BucketOwnerFullControl
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  s3Bucket:
    Description: "s3 bucket ARN"
    Value: !GetAtt s3Bucket.Arn
#  HelloWorldFunctionIamRole:
#    Description: "Implicit IAM Role created for Hello World function"
#    Value: !GetAtt HelloWorldFunctionRole.Arn


#
##  DeveloperUser:
##    Type: 'AWS::IAM::User'
##    Properties:
##      UserName: user-developer
##      ManagedPolicyArns:
##        - 'arn:aws:iam::aws:policy/AWSServiceCatalogEndUserFullAccess'
##        - 'arn:aws:iam::aws:policy/ReadOnlyAccess'
##        - 'arn:aws:iam::aws:policy/CloudWatchFullAccess'
##        - 'arn:aws:iam::aws:policy/AmazonVPCFullAccess'
##        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'


##Outputs:

##    Description: "Hello World Lambda Function ARN"
##    Value: !GetAtt HelloWorldFunction.Arn
##  HelloWorldFunctionIamRole:
##    Description: "Implicit IAM Role created for Hello World function"
##    Value: !GetAtt HelloWorldFunctionRole.Arn
